#let's talk confidence intervals of proportions 
#we'll use the function "binom.confint() which is part of the binom package
#install and load binom
#install.packages("binom")
library(binom)

#what is the 95% CI of O'Rourke
#usage if binom.confint(successes,trials,confidence level, method).
#We'll calculate a 95% confidence intveral using the agresti-coull method recommended by your texbook. 

#the observed number of successes was sampe size * proportion
483*0.01
# we'll be generous and round up to 5
#The abbreviation for agresti-coull is "ac"
binom.confint(5,483,0.95,"ac")
## go ahead and calculate the 95% confidence interval on support for the candidate of your choosing.
483*0.11
binom.confint(54,483,0.95,"ac")

estimated_proportionLost <- (101)/240
binom.confint(101,210,0.95,"ac")
#you try problem #2 on your own.
#
#
#
#
binom.confint(101,240,0.95,"ac")
#function dbinom() calculates the probability of a given number of success, in a given number of trials, based on an overall probability of success based on the binomial distribution
#its usage is: dbinom(#success,#trials,probability)
#Let's consider practice problem 3.
dbinom(5,7,0.3)
#this is the probability of 5 successes. How do we calculate the probability of 5 or more successes?
dbinom(5,7,0.3) + dbinom(6,7,0.3) + dbinom(7,7,0.3)
#to make this EVEN EASIER, we can calculate the cumulative probability of 5,6, or 7 succeses with pbinom()
#usage of pbinom is pbinom(#success,#trials,probability), where # of successes indicates the boundary on the number of successes.
#if you are interested in the upper tail (probability of n or more successes), then pbinom is used as pbinom(n-1,#trials,probability,lower.tail=FALSE)
pbinom(4,7,0.3,lower.tail=FALSE)
#if you are interested in the lower tail (probability of n or fewer successes), then pbinom is used as pbinom(n,#trials,probability,lower.tail=TRUE)
pbinom(4,7,0.3,lower.tail=TRUE)
#you can make this EVEN EASIER using binom.test(), which calculates a P-value for the observed # of success of a bernoulli trial
#binom.test usage is binom.test(#successes,#trials,probability,P-value type,significance level)
binom.test(5,7,0.3,"two.sided",0.05)
#note that the confidence interval reported in binomial test are not generated by the Agresti-Coull method that is recommended by your textbook preferred method indicated by your textbook
#why is the P-value NOT 2x the cumulative probability of the right tail of the distribution?
#Let's plot the distribution and consider
successes <- seq(0,7,by=1)
probabilities <- dbinom(successes,7,0.3)
#mean - no of trials * probability= 2.1
#5-2.1 = 2.9
#2.1-2.9
dbinom(6,25,0.5)

bi.df <- data.frame(successes,probabilities)
ggplot(bi.df, aes(successes,probabilities)) + geom_bar(stat="identity")
#note that this distribution is not symmetric, since it is bounded from 0.7 and p is not 0.5
#together with your classmates, you try problem #4.
#
#
binom.test(1,2,0.5106)
#HYPOTHESIS TESTING NULL HYP-0.5
binom.test(19,25,0.5)
binom.test(6,25,0.5)
binom.test(350,1000,0.2)
NULL_HYP <- 1/11
0.01*483
binom.test(5,483,0.0909)
binom.confint(4,10,0.95,"ac")

binom.test(4,10,0.2)
binom.confint(5,12,0.95,"ac")
binom.confint(5,483,0.95,"ac")
#null hyp is rejected.